import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";

export default function Layout({ children, title }) {
  return (
    <>
      <div>
        <Head>
          <title>{title ? title + " - VOOK" : "VOOK"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className="flex min-h-screen flex-col justify-between items-center bg-[#f7feff]">
          <div className="container m-auto mt-4 px-4">
            
            <main>{children}</main>
            <footer className="bg-red-400 h-2 w-full"></footer>
          </div>
        </div>
      </div>
    </>
  );
}
